from pathlib import PurePosixPath
from typing import Final

__all__ = ['ASSEMBLY_GENERATOR', 'NODE_PACK_GENERATOR', 'ASSEMBLY_ROOT', 'NODE_PACK_ROOT', 'MANIFEST_MEMBER_NAME', 'COVERAGE_MEMBER_NAME', 'NORMALIZED_SCALE_DIRECTORY', 'HIGH_FANOUT_RELATIONSHIPS_MEMBER_NAME', 'RELATIONSHIP_MUTATIONS_MEMBER_NAME', 'CTF_METADATA_MEMBER', 'CTF_STREAM_MEMBER', 'ASSEMBLY_MANIFEST_MEMBER', 'ASSEMBLY_COVERAGE_MEMBER', 'NODE_PACK_MANIFEST_MEMBER', 'NORMALIZED_SCALE_PREFIX', 'NORMALIZED_SCALE_MANIFEST_MEMBER', 'normalize_archive_member_name']

ASSEMBLY_GENERATOR: str
NODE_PACK_GENERATOR: str
ASSEMBLY_ROOT: str
NODE_PACK_ROOT: str
MANIFEST_MEMBER_NAME: str
COVERAGE_MEMBER_NAME: str
NORMALIZED_SCALE_DIRECTORY: str
HIGH_FANOUT_RELATIONSHIPS_MEMBER_NAME: str
RELATIONSHIP_MUTATIONS_MEMBER_NAME: str
CTF_METADATA_MEMBER: str
CTF_STREAM_MEMBER: str
ASSEMBLY_MANIFEST_MEMBER: Final[str]
ASSEMBLY_COVERAGE_MEMBER: Final[str]
NODE_PACK_MANIFEST_MEMBER: Final[str]
NORMALIZED_SCALE_PREFIX: Final[str]
NORMALIZED_SCALE_MANIFEST_MEMBER: Final[str]

def normalize_archive_member_name(logical_name: str) -> PurePosixPath: ...
