from .assembly_store import DemoAssemblyStore as DemoAssemblyStore
from .scale_data import ScaleRuntime as ScaleRuntime
from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any, Mapping

REVISION_ID: str

def current_revision_store() -> DemoAssemblyStore: ...
@contextmanager
def revision_store_scope(store: DemoAssemblyStore) -> Iterator[None]: ...
@contextmanager
def demo_revision_scope(revision_id: str) -> Iterator[None]: ...

DEMO_GAPS: list[dict[str, Any]]
REVIEW_PROMPTS: list[str]

def load_demo_dataset(revision_id: str | None = None, *, node_id: str | None = None) -> dict[str, Any]: ...
def scale_runtime(dataset: Mapping[str, Any] | None = None) -> ScaleRuntime | None: ...
def dataset_revision_id(dataset: Mapping[str, Any] | None = None) -> str: ...
def analysis_metadata(dataset: Mapping[str, Any]) -> dict[str, Any]: ...
def is_scale_dataset(dataset: Mapping[str, Any] | None = None) -> bool: ...
def workspace_metadata(dataset: Mapping[str, Any], *, revision_id: str, history_mode: str) -> dict[str, Any]: ...
def route_resolution_capability(dataset: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
def generated_route_row(route_id: str, dataset: Mapping[str, Any] | None = None) -> dict[str, Any]: ...
