from typing import Any, Final

RESOURCE_TABLE_COLUMNS: Final[tuple[str, ...]]
RESOURCE_TABLE_JSON_COLUMNS: Final[tuple[str, ...]]

def scale_condition_class(status: Any) -> str: ...
def scale_resource_label(resource_id: str) -> str: ...
def scale_resource_record(values: tuple[str, ...], *, key_json: str = '', state_json: str = '') -> dict[str, Any]: ...
def scale_icon_descriptor(kind: str, scale_descriptors: dict[str, dict[str, Any]]) -> dict[str, Any]: ...
def scale_relationship_descriptor(relation_type: str, structural: bool) -> dict[str, Any]: ...
def scale_dashboards(event_count: int) -> list[dict[str, Any]]: ...
def scale_projection_capabilities(plugin_schema: dict[str, Any]) -> dict[str, dict[str, Any]]: ...
def scale_initial_resource_ids(walkthrough: dict[str, Any], resources_by_kind: dict[str, list[dict[str, Any]]]) -> list[str]: ...
