"""Generate the vendored emoji variation-pair table used by public text.

This is a development-time maintenance tool.  The application imports only
the generated Python module and never fetches Unicode data at runtime.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import urllib.request
from pathlib import Path

DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "router_dump_analyzer"
    / "_emoji_variation_sequences.py"
)
_PAIR_LINE = re.compile(rb"^([0-9A-F]+) (FE0[EF])\s*;", re.MULTILINE)
_EMOJI_VERSION = re.compile(rb"Used with Emoji Version ([0-9.]+)")
_SOURCE_DATE = re.compile(rb"^# Date: ([^\r\n]+)", re.MULTILINE)


def _default_source_url() -> str:
    """Return the generated module's pinned upstream source location."""

    # Keep the named contract constant in the generated runtime module as its
    # single production owner.  This maintenance script deliberately computes
    # its default rather than declaring a second uppercase contract constant.
    return (
        "https://www.unicode.org/Public/15.0.0/ucd/emoji/"
        "emoji-variation-sequences.txt"
    )


def _read_source(source: str) -> bytes:
    path = Path(source)
    if path.is_file():
        return path.read_bytes()
    if not source.startswith("https://www.unicode.org/"):
        raise ValueError("source must be a local file or an official Unicode HTTPS URL")
    with urllib.request.urlopen(source, timeout=30) as response:
        return response.read()


def _parse_source(raw: bytes) -> tuple[tuple[tuple[int, int], ...], str, str]:
    pairs = tuple(
        (int(match.group(1), 16), int(match.group(2), 16))
        for match in _PAIR_LINE.finditer(raw)
    )
    if not pairs or len(pairs) != len(set(pairs)):
        raise ValueError("Unicode source has no pairs or contains duplicate pairs")
    selectors_by_base: dict[int, set[int]] = {}
    for base, selector in pairs:
        selectors_by_base.setdefault(base, set()).add(selector)
    expected_selectors = {0xFE0E, 0xFE0F}
    if any(selectors != expected_selectors for selectors in selectors_by_base.values()):
        raise ValueError(
            "generated representation requires both FE0E and FE0F for every base"
        )
    emoji_version_match = _EMOJI_VERSION.search(raw)
    source_date_match = _SOURCE_DATE.search(raw)
    if emoji_version_match is None or source_date_match is None:
        raise ValueError("Unicode source is missing required version metadata")
    return (
        pairs,
        emoji_version_match.group(1).decode("ascii"),
        source_date_match.group(1).decode("utf-8"),
    )


def _render(
    *,
    pairs: tuple[tuple[int, int], ...],
    source: str,
    source_sha256: str,
    emoji_version: str,
    source_date: str,
) -> str:
    bases = sorted({base for base, _selector in pairs})
    base_lines = "\n".join(f"    0x{base:04X}," for base in bases)
    return f'''"""Generated Unicode emoji presentation variation pairs.

Generated by ``scripts/generate_emoji_variation_sequences.py``.  Do not edit
this module by hand.  Refresh it from the pinned official source and review
the metadata and policy tests in the same change.
"""

from __future__ import annotations

UNICODE_VERSION = "15.0.0"
EMOJI_VERSION = {emoji_version!r}
SOURCE_URL = {source!r}
SOURCE_DATE = {source_date!r}
SOURCE_SHA256 = {source_sha256!r}
SOURCE_PAIR_COUNT = {len(pairs)}

_EMOJI_VARIATION_BASE_CODEPOINTS = (
{base_lines}
)

# Unicode 15.0 registers both text and emoji presentation for every base in
# this data file.  The generator rejects a future asymmetric source instead
# of silently broadening this exact-pair representation.
EMOJI_VARIATION_SEQUENCE_PAIRS = frozenset(
    (base, selector)
    for base in _EMOJI_VARIATION_BASE_CODEPOINTS
    for selector in (0xFE0E, 0xFE0F)
)
assert len(EMOJI_VARIATION_SEQUENCE_PAIRS) == SOURCE_PAIR_COUNT

__all__ = [
    "EMOJI_VARIATION_SEQUENCE_PAIRS",
    "EMOJI_VERSION",
    "SOURCE_DATE",
    "SOURCE_PAIR_COUNT",
    "SOURCE_SHA256",
    "SOURCE_URL",
    "UNICODE_VERSION",
]
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=_default_source_url())
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    raw = _read_source(args.source)
    pairs, emoji_version, source_date = _parse_source(raw)
    rendered = _render(
        pairs=pairs,
        source=args.source,
        source_sha256=hashlib.sha256(raw).hexdigest(),
        emoji_version=emoji_version,
        source_date=source_date,
    )
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
