from dataclasses import dataclass
from pathlib import Path
from rsl_demo_plugin.archive import normalize_archive_member_name as validate_archive_name
from typing import Any, Mapping

__all__ = ['validate_archive_name', 'DETERMINISTIC_GZIP_LEVEL', 'json_bytes', 'ArchiveWriteResult', 'deterministic_tgz_bytes', 'write_deterministic_tgz', 'directory_members']

DETERMINISTIC_GZIP_LEVEL: int

def json_bytes(value: Any) -> bytes: ...

@dataclass(frozen=True, slots=True)
class ArchiveWriteResult:
    sha256: str
    size: int

class _DigestingWriter:
    size: int
    def __init__(self, output: Any) -> None: ...
    def write(self, content: bytes) -> int: ...
    def flush(self) -> None: ...
    def tell(self) -> int: ...
    @property
    def sha256(self) -> str: ...

def deterministic_tgz_bytes(files: Mapping[str, bytes]) -> bytes: ...
def write_deterministic_tgz(output: Path, members: Mapping[str, Path]) -> ArchiveWriteResult: ...
def directory_members(directory: Path) -> dict[str, Path]: ...
